In [46]:
import pandas as pd
import numpy as np

In [47]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [48]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [49]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [50]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [51]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [52]:
X_train.shape

(4457,)

In [53]:
X_test.shape

(1115,)

In [54]:
type(X_train)

pandas.core.series.Series

In [55]:
X_train[:4]

137                    He is there. You call and meet him
1340            Every monday..nxt week vl be completing..
158     Hello, my love. What are you doing? Did you ge...
973                 Yup i thk so until e shop closes lor.
Name: Message, dtype: object

In [56]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58758 stored elements and shape (4457, 7708)>

In [57]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [58]:
v.get_feature_names_out().shape

(7708,)

In [59]:
v.vocabulary_

{'he': 3348,
 'is': 3718,
 'there': 6809,
 'you': 7667,
 'call': 1610,
 'and': 960,
 'meet': 4389,
 'him': 3414,
 'every': 2652,
 'monday': 4532,
 'nxt': 4833,
 'week': 7408,
 'vl': 7286,
 'be': 1274,
 'completing': 1935,
 'hello': 3379,
 'my': 4631,
 'love': 4191,
 'what': 7444,
 'are': 1048,
 'doing': 2382,
 'did': 2286,
 'get': 3106,
 'to': 6912,
 'that': 6786,
 'interview': 3684,
 'today': 6918,
 'happy': 3317,
 'being': 1308,
 'good': 3169,
 'boy': 1476,
 'do': 2358,
 'think': 6823,
 'of': 4857,
 'me': 4370,
 'missing': 4478,
 'yup': 7692,
 'thk': 6833,
 'so': 6257,
 'until': 7152,
 'shop': 6079,
 'closes': 1855,
 'lor': 4171,
 'it': 3729,
 'not': 4798,
 'make': 4290,
 'cry': 2085,
 'just': 3838,
 'when': 7451,
 'all': 911,
 'our': 4975,
 'stuff': 6520,
 'happens': 3313,
 'on': 4902,
 'top': 6956,
 'everything': 2660,
 'else': 2548,
 'pushes': 5474,
 'over': 4996,
 'the': 6789,
 'edge': 2508,
 'don': 2390,
 'underdtand': 7114,
 'how': 3495,
 'often': 4874,
 'sorry': 6308,
 'life':

In [60]:
X_train_np = X_train_cv.toarray()
X_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [61]:
np.where(X_train_np[0]!=0)

(array([ 960, 1610, 3348, 3414, 3718, 4389, 6809, 7667]),)

In [62]:
X_train[:4]

137                    He is there. You call and meet him
1340            Every monday..nxt week vl be completing..
158     Hello, my love. What are you doing? Did you ge...
973                 Yup i thk so until e shop closes lor.
Name: Message, dtype: object

In [63]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [64]:
X_test_cv= v.transform(X_test)

In [67]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       971
           1       0.99      0.94      0.96       144

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [68]:
emails = [
    'Hey mohan, can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [70]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [71]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [74]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       971
           1       0.99      0.94      0.96       144

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

